(function () {
  const categories = [
    { id: "coffee", name: "Coffee", label: "커피", description: "에스프레소 기반의 기본 메뉴" },
    { id: "latte", name: "Latte", label: "라떼", description: "우유와 크림이 어우러진 부드러운 메뉴" },
    { id: "tea", name: "Tea", label: "티", description: "가볍게 즐기는 차와 허브 음료" },
    { id: "dessert", name: "Dessert", label: "디저트", description: "상큼한 레몬 향 가득한 시그니처 디저트" },
  ];

  const menus = [
    {
      id: "americano",
      categoryId: "coffee",
      name: "아메리카노",
      englishName: "Americano",
      price: 4500,
      image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80",
      description: "깊고 깔끔한 산미가 살아 있는 기본 커피입니다.",
      tags: ["best", "hot", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "cafe-latte",
      categoryId: "latte",
      name: "카페라떼",
      englishName: "Cafe Latte",
      price: 5200,
      image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=900&q=80",
      description: "고소한 우유와 에스프레소가 균형 있게 어우러집니다.",
      tags: ["signature", "hot", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "vanilla-latte",
      categoryId: "latte",
      name: "바닐라 라떼",
      englishName: "Vanilla Latte",
      price: 5800,
      image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80",
      description: "은은한 바닐라 향을 더한 달콤한 라떼입니다.",
      tags: ["sweet", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "earl-grey",
      categoryId: "tea",
      name: "얼그레이 티",
      englishName: "Earl Grey Tea",
      price: 4800,
      image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=900&q=80",
      description: "베르가못 향이 산뜻하게 퍼지는 클래식 티입니다.",
      tags: ["hot", "light"],
      options: {
        temperature: ["hot"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "green-tea-latte",
      categoryId: "latte",
      name: "말차 라떼",
      englishName: "Green Tea Latte",
      price: 5900,
      image: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=900&q=80",
      description: "진한 말차와 우유의 부드러운 맛을 살렸습니다.",
      tags: ["signature", "sweet"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "lemon-butter-croissant",
      categoryId: "dessert",
      name: "레몬 버터 크루아상",
      englishName: "Lemon Butter Croissant",
      price: 4500,
      image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
      description: "겹겹이 바삭한 크루아상에 레몬 버터를 발라낸 시그니처 베이커리입니다.",
      tags: ["bakery", "morning", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-tart",
      categoryId: "dessert",
      name: "레몬 타르트",
      englishName: "Lemon Tart",
      price: 5800,
      image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583a?auto=format&fit=crop&w=900&q=80",
      description: "바삭한 타르트 시트 위에 상큼한 레몬 커드를 가득 채운 시그니처 디저트입니다.",
      tags: ["signature", "sour", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "lemon-madeleine",
      categoryId: "dessert",
      name: "레몬 마들렌",
      englishName: "Lemon Madeleine",
      price: 4200,
      image: "https://images.unsplash.com/photo-1558326567-98ae2405596b?auto=format&fit=crop&w=900&q=80",
      description: "레몬 제스트를 더해 은은한 향이 살아있는 조개 모양 구움과자입니다.",
      tags: ["sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-pound-cake",
      categoryId: "dessert",
      name: "레몬 파운드케이크",
      englishName: "Lemon Pound Cake",
      price: 5200,
      image: "https://images.unsplash.com/photo-1607478900766-efe13248b125?auto=format&fit=crop&w=900&q=80",
      description: "촉촉한 버터 케이크에 레몬 글레이즈를 입혀 산뜻하게 마무리했습니다.",
      tags: ["sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-cheesecake",
      categoryId: "dessert",
      name: "레몬 치즈케이크",
      englishName: "Lemon Cheesecake",
      price: 6500,
      image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=900&q=80",
      description: "진한 크림치즈에 레몬의 산미를 더해 느끼하지 않고 깔끔합니다.",
      tags: ["signature", "sour", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "lemon-bar",
      categoryId: "dessert",
      name: "레몬 바",
      englishName: "Lemon Bar",
      price: 4800,
      image: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=900&q=80",
      description: "쇼트브레드 위에 새콤달콤한 레몬 필링을 올린 한입 디저트입니다.",
      tags: ["sour", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-macaron",
      categoryId: "dessert",
      name: "레몬 마카롱",
      englishName: "Lemon Macaron",
      price: 3200,
      image: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=900&q=80",
      description: "레몬 커드를 필링으로 채운 프랑스식 마카롱입니다.",
      tags: ["sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-scone",
      categoryId: "dessert",
      name: "레몬 스콘",
      englishName: "Lemon Scone",
      price: 4500,
      image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=900&q=80",
      description: "레몬 제스트를 반죽에 넣어 구운 담백하고 향긋한 스콘입니다.",
      tags: ["lemon", "morning"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-roll-cake",
      categoryId: "dessert",
      name: "레몬 롤케이크",
      englishName: "Lemon Roll Cake",
      price: 5900,
      image: "https://images.unsplash.com/photo-1519654793190-2718bcc1c98d?auto=format&fit=crop&w=900&q=80",
      description: "부드러운 시트에 레몬 크림을 돌돌 말아 넣은 롤케이크입니다.",
      tags: ["sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-cookie",
      categoryId: "dessert",
      name: "레몬 쿠키",
      englishName: "Lemon Cookie",
      price: 3800,
      image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583a?auto=format&fit=crop&w=900&q=80",
      description: "화이트 초콜릿과 레몬 제스트가 어우러진 쫀득한 쿠키입니다.",
      tags: ["sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-curd-toast",
      categoryId: "dessert",
      name: "레몬 커드 토스트",
      englishName: "Lemon Curd Toast",
      price: 6200,
      image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=80",
      description: "두툼한 브리오슈 토스트에 레몬 커드와 크림치즈를 듬뿍 올렸습니다.",
      tags: ["signature", "sour", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-mousse-cake",
      categoryId: "dessert",
      name: "레몬 무스케이크",
      englishName: "Lemon Mousse Cake",
      price: 6800,
      image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80",
      description: "가볍고 부드러운 레몬 무스와 스펀지 시트를 층층이 쌓았습니다.",
      tags: ["signature", "sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "lemon-sorbet",
      categoryId: "dessert",
      name: "레몬 셔벗",
      englishName: "Lemon Sorbet",
      price: 4500,
      image: "https://images.unsplash.com/photo-1560801619-01e0c3cf7cf9?auto=format&fit=crop&w=900&q=80",
      description: "레몬 과즙으로 만들어 입안이 개운해지는 시원한 셔벗입니다.",
      tags: ["sour", "lemon", "iced"],
      options: {
        temperature: ["frozen"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-cream-pie",
      categoryId: "dessert",
      name: "레몬 크림파이",
      englishName: "Lemon Cream Pie",
      price: 6300,
      image: "https://images.unsplash.com/photo-1541599468348-e96984315921?auto=format&fit=crop&w=900&q=80",
      description: "바삭한 파이 크러스트에 레몬 크림과 머랭을 올려 구워냈습니다.",
      tags: ["signature", "sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-butter-cookie",
      categoryId: "dessert",
      name: "레몬 버터쿠키",
      englishName: "Lemon Butter Cookie",
      price: 3500,
      image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=900&q=80",
      description: "고소한 버터 쿠키에 레몬 아이싱을 더한 티타임 디저트입니다.",
      tags: ["sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-drizzle-cake",
      categoryId: "dessert",
      name: "레몬 드리즐 케이크",
      englishName: "Lemon Drizzle Cake",
      price: 7200,
      image: "https://images.unsplash.com/photo-1592151441516-3d0ff945bf6c?auto=format&fit=crop&w=900&q=80",
      description: "구운 케이크 위에 새콤달콤한 레몬 시럽을 듬뿍 끼얹은 시그니처 케이크입니다.",
      tags: ["signature", "sour", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
  ];

  const orders = [];

  window.CafeData = Object.freeze({
    categories,
    menus,
    orders,
  });
})();
