(function () {
  const categories = [
    { id: "coffee", name: "Coffee", label: "커피", description: "에스프레소 베이스의 커피" },
    { id: "tea", name: "Tea", label: "티", description: "따뜻하게 즐기는 차" },
    { id: "beverage", name: "Beverage", label: "음료", description: "다양하게 즐기는 음료" },
    { id: "ade", name: "Ade", label: "에이드", description: "상큼한 에이드" },
    { id: "smoothie", name: "Smoothie", label: "스무디", description: "부드러운 스무디" },
    { id: "dessert", name: "Dessert", label: "디저트", description: "베이커리와 디저트" },
  ];

  const PLACEHOLDER_IMAGE = "/images/menu/placeholder.svg";

  const menus = [
    {
      id: "espresso",
      categoryId: "coffee",
      name: "에스프레소",
      englishName: "Espresso",
      price: { single: 3800 },
      image: "/images/menu/espresso.jpg",
      description: "깊고 진한 풍미의 기본 에스프레소입니다.",
      tags: ["hot"],
      options: { temperature: ["hot"], sizes: ["single"] },
      addons: [
        { id: "extraShot", label: "샷 추가", price: 500 },
        { id: "decaf", label: "디카페인 변경", price: 500 },
      ],
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "americano",
      categoryId: "coffee",
      name: "아메리카노",
      englishName: "Americano",
      price: { regular: 3800, large: 4300 },
      image: "/images/menu/americano.jpg",
      description: "깔끔한 산미가 살아 있는 기본 커피입니다.",
      tags: ["best", "hot", "iced"],
      options: { temperature: ["hot", "iced"], sizes: ["regular", "large"] },
      addons: [
        { id: "extraShot", label: "샷 추가", price: 500 },
        { id: "decaf", label: "디카페인 변경", price: 500 },
      ],
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "cafe-latte",
      categoryId: "coffee",
      name: "카페라떼",
      englishName: "Cafe Latte",
      price: { regular: 4300, large: 4800 },
      image: "/images/menu/cafe-latte.jpg",
      description: "고소한 우유와 에스프레소가 균형 있게 어우러집니다.",
      tags: ["signature", "hot", "iced"],
      options: { temperature: ["hot", "iced"], sizes: ["regular", "large"] },
      addons: [
        { id: "extraShot", label: "샷 추가", price: 500 },
        { id: "decaf", label: "디카페인 변경", price: 500 },
      ],
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "cafe-mocha",
      categoryId: "coffee",
      name: "카페모카",
      englishName: "Cafe Mocha",
      price: { regular: 4800, large: 5300 },
      image: "/images/menu/cafe-mocha.jpg",
      description: "달콤한 초콜릿과 에스프레소가 만난 진한 커피입니다.",
      tags: ["sweet", "hot", "iced"],
      options: { temperature: ["hot", "iced"], sizes: ["regular", "large"] },
      addons: [
        { id: "extraShot", label: "샷 추가", price: 500 },
        { id: "decaf", label: "디카페인 변경", price: 500 },
      ],
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "vanilla-latte",
      categoryId: "coffee",
      name: "바닐라라떼",
      englishName: "Vanilla Latte",
      price: { regular: 4800, large: 5300 },
      image: "/images/menu/vanilla-latte.jpg",
      description: "은은한 바닐라 향을 더한 달콤한 라떼입니다.",
      tags: ["sweet", "hot", "iced"],
      options: { temperature: ["hot", "iced"], sizes: ["regular", "large"] },
      addons: [
        { id: "extraShot", label: "샷 추가", price: 500 },
        { id: "decaf", label: "디카페인 변경", price: 500 },
      ],
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "black-sesame-cream-latte",
      categoryId: "coffee",
      name: "흑임자크림라떼",
      englishName: "Black Sesame Cream Latte",
      price: { single: 6000 },
      image: "/images/menu/black-sesame-cream-latte.jpg",
      description: "고소한 흑임자와 부드러운 크림이 올라간 시그니처 라떼입니다.",
      tags: ["signature", "hot", "iced"],
      options: { temperature: ["hot", "iced"], sizes: ["single"] },
      addons: [
        { id: "extraShot", label: "샷 추가", price: 500 },
        { id: "decaf", label: "디카페인 변경", price: 500 },
      ],
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "hand-drip",
      categoryId: "coffee",
      name: "핸드드립",
      englishName: "Hand Drip Coffee",
      price: { single: 6000 },
      image: "/images/menu/hand-drip.jpg",
      description: "한 잔씩 정성스럽게 내린 핸드드립 커피입니다.",
      tags: ["signature", "hot"],
      options: { temperature: ["hot"], sizes: ["single"] },
      addons: [
        { id: "extraShot", label: "샷 추가", price: 500 },
        { id: "decaf", label: "디카페인 변경", price: 500 },
      ],
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "chamomile",
      categoryId: "tea",
      name: "캐모마일",
      englishName: "Chamomile Tea",
      price: { single: 6500 },
      image: "/images/menu/chamomile.jpg",
      description: "은은한 꽃향으로 편안하게 즐기는 허브티입니다.",
      tags: ["hot"],
      options: { temperature: ["hot"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "peach-oolong",
      categoryId: "tea",
      name: "피치우롱",
      englishName: "Peach Oolong Tea",
      price: { single: 6500 },
      image: "/images/menu/peach-oolong.jpg",
      description: "복숭아 향이 은은하게 어우러진 우롱차입니다.",
      tags: ["hot"],
      options: { temperature: ["hot"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "peppermint-rooibos",
      categoryId: "tea",
      name: "페퍼민트 루이보스",
      englishName: "Peppermint Rooibos Tea",
      price: { single: 6500 },
      image: "/images/menu/peppermint-rooibos.jpg",
      description: "티팟에 드립니다. 얼음잔 요청 가능합니다.",
      tags: ["hot"],
      options: { temperature: ["hot"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-grapefruit-tea",
      categoryId: "tea",
      name: "레몬/자몽티",
      englishName: "Lemon/Grapefruit Tea",
      price: { single: 5500 },
      image: "/images/menu/lemon-grapefruit-tea.jpg",
      description: "상큼한 레몬 또는 자몽으로 만든 따뜻한 차입니다.",
      tags: ["hot"],
      options: { temperature: ["hot"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "jujube-tea",
      categoryId: "tea",
      name: "대추고음차",
      englishName: "Jujube Tea",
      price: { single: 6500 },
      image: "/images/menu/jujube-tea.jpg",
      description: "오랜 시간 고아낸 대추로 깊은 맛을 낸 차입니다.",
      tags: ["hot"],
      options: { temperature: ["hot"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "ssanghwa-tea",
      categoryId: "tea",
      name: "쌍화차",
      englishName: "Ssanghwa Tea",
      price: { single: 6500 },
      image: "/images/menu/ssanghwa-tea.jpg",
      description: "한약재를 우려낸 깊고 진한 전통차입니다.",
      tags: ["hot"],
      options: { temperature: ["hot"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "sikhye",
      categoryId: "beverage",
      name: "점례식혜",
      englishName: "Sikhye",
      price: { regular: 6000, large: 12000 },
      image: "/images/menu/sikhye.jpg",
      description: "은은한 단맛의 전통 식혜입니다. Large는 1L 대용량입니다.",
      tags: ["signature", "iced"],
      options: { temperature: ["iced"], sizes: ["regular", "large"] },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "peach-mango-ice-tea",
      categoryId: "beverage",
      name: "피치망고아이스티",
      englishName: "Peach Mango Iced Tea",
      price: { single: 5000 },
      image: "/images/menu/peach-mango-ice-tea.jpg",
      description: "복숭아와 망고의 달콤함이 어우러진 아이스티입니다.",
      tags: ["iced"],
      options: { temperature: ["iced"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "choco-latte",
      categoryId: "beverage",
      name: "초코라떼",
      englishName: "Choco Latte",
      price: { regular: 4800, large: 5300 },
      image: "/images/menu/choco-latte.jpg",
      description: "진한 초콜릿과 우유가 어우러진 달콤한 라떼입니다.",
      tags: ["sweet", "hot", "iced"],
      options: { temperature: ["hot", "iced"], sizes: ["regular", "large"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "green-tea-latte",
      categoryId: "beverage",
      name: "녹차라떼",
      englishName: "Green Tea Latte",
      price: { regular: 4800, large: 5300 },
      image: "/images/menu/green-tea-latte.jpg",
      description: "진한 녹차와 우유의 부드러운 맛을 살렸습니다.",
      tags: ["sweet", "hot", "iced"],
      options: { temperature: ["hot", "iced"], sizes: ["regular", "large"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-ade",
      categoryId: "ade",
      name: "레몬에이드",
      englishName: "Lemon Ade",
      price: { single: 5500 },
      image: "/images/menu/lemon-ade.jpg",
      description: "생레몬을 직접 짜서 만든 새콤달콤한 에이드입니다.",
      tags: ["signature", "iced"],
      options: { temperature: ["iced"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "grapefruit-ade",
      categoryId: "ade",
      name: "자몽에이드",
      englishName: "Grapefruit Ade",
      price: { single: 5500 },
      image: "/images/menu/grapefruit-ade.jpg",
      description: "새콤달콤한 자몽으로 만든 시그니처 에이드입니다.",
      tags: ["iced"],
      options: { temperature: ["iced"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "passion-fruit-ade",
      categoryId: "ade",
      name: "패션후르츠에이드",
      englishName: "Passion Fruit Ade",
      price: { single: 5500 },
      image: "/images/menu/passion-fruit-ade.jpg",
      description: "새콤한 패션후르츠 과육이 가득한 에이드입니다.",
      tags: ["iced"],
      options: { temperature: ["iced"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "yogurt-smoothie",
      categoryId: "smoothie",
      name: "요거트스무디",
      englishName: "Yogurt Smoothie",
      price: { single: 6000 },
      image: "/images/menu/yogurt-smoothie.jpg",
      description: "상큼한 요거트로 만든 부드러운 스무디입니다.",
      tags: ["iced"],
      options: { temperature: ["iced"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "strawberry-smoothie",
      categoryId: "smoothie",
      name: "딸기스무디",
      englishName: "Strawberry Smoothie",
      price: { single: 6500 },
      image: "/images/menu/strawberry-smoothie.jpg",
      description: "달콤한 딸기로 만든 진한 스무디입니다.",
      tags: ["iced"],
      options: { temperature: ["iced"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "mango-smoothie",
      categoryId: "smoothie",
      name: "망고스무디",
      englishName: "Mango Smoothie",
      price: { single: 6500 },
      image: "/images/menu/mango-smoothie.jpg",
      description: "잘 익은 망고로 만든 부드러운 스무디입니다.",
      tags: ["iced"],
      options: { temperature: ["iced"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-scone",
      categoryId: "dessert",
      name: "레몬스콘",
      englishName: "Lemon Scone",
      price: { single: 3000 },
      image: "/images/menu/scone.jpg",
      description: "상큼한 레몬이 들어간 촉촉한 스콘입니다.",
      tags: ["bakery"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "earl-grey-scone",
      categoryId: "dessert",
      name: "얼그레이스콘",
      englishName: "Earl Grey Scone",
      price: { single: 3000 },
      image: "/images/menu/scone.jpg",
      description: "은은한 얼그레이 향이 나는 촉촉한 스콘입니다.",
      tags: ["bakery"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "original-levain-cookie",
      categoryId: "dessert",
      name: "오리지널 르뱅쿠키",
      englishName: "Original Levain Cookie",
      price: { single: 3500 },
      image: "/images/menu/levain-cookie.jpg",
      description: "겉은 바삭하고 속은 촉촉한 오리지널 르뱅쿠키입니다.",
      tags: ["bakery"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "pecan-choco-levain-cookie",
      categoryId: "dessert",
      name: "피칸초코 르뱅쿠키",
      englishName: "Pecan Choco Levain Cookie",
      price: { single: 3500 },
      image: "/images/menu/levain-cookie.jpg",
      description: "고소한 피칸과 진한 초콜릿이 들어간 르뱅쿠키입니다.",
      tags: ["bakery"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "white-matcha-levain-cookie",
      categoryId: "dessert",
      name: "화이트말차 르뱅쿠키",
      englishName: "White Matcha Levain Cookie",
      price: { single: 3500 },
      image: "/images/menu/levain-cookie.jpg",
      description: "화이트초콜릿과 말차가 어우러진 르뱅쿠키입니다.",
      tags: ["bakery"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "salt-bread",
      categoryId: "dessert",
      name: "소금식빵",
      englishName: "Salt Bread",
      price: { single: 5000 },
      image: "/images/menu/salt-bread.jpg",
      description: "겉은 짭짤하고 속은 부드러운 식빵입니다.",
      tags: ["bakery"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "earl-grey-cake",
      categoryId: "dessert",
      name: "얼그레이 케이크",
      englishName: "Earl Grey Cake",
      price: { single: 5800 },
      image: "/images/menu/earl-grey-cake.jpg",
      description: "은은한 얼그레이 향이 나는 조각 케이크입니다.",
      tags: ["bakery", "signature"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "lemon-meringue-cake",
      categoryId: "dessert",
      name: "레몬 머랭 케이크",
      englishName: "Lemon Meringue Cake",
      price: { single: 6500 },
      image: "/images/menu/lemon-meringue-cake.jpg",
      description: "새콤한 레몬 커드와 부드러운 머랭이 올라간 케이크입니다.",
      tags: ["bakery", "signature"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "basil-ciabatta-sandwich",
      categoryId: "dessert",
      name: "바질 치아바타 샌드위치",
      englishName: "Basil Ciabatta Sandwich",
      price: { single: 8500 },
      image: "/images/menu/basil-ciabatta-sandwich.jpg",
      description: "바질 치아바타 빵에 햄, 치즈, 채소를 가득 채운 샌드위치입니다.",
      tags: ["bakery"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "egg-apple-ciabatta-sandwich",
      categoryId: "dessert",
      name: "에그 애플 치아바타 샌드위치",
      englishName: "Egg Apple Ciabatta Sandwich",
      price: { single: 9000 },
      image: "/images/menu/egg-apple-ciabatta-sandwich.jpg",
      description: "반숙 에그와 아삭한 사과가 들어간 치아바타 샌드위치입니다.",
      tags: ["bakery"],
      options: { temperature: ["room"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "patbingsu",
      categoryId: "dessert",
      name: "팥빙수",
      englishName: "Patbingsu",
      price: { single: 12000 },
      image: "/images/menu/patbingsu.jpg",
      description: "고운 얼음 위에 팥, 인절미, 콩고물을 듬뿍 올린 빙수입니다.",
      tags: ["bakery", "signature", "iced"],
      options: { temperature: ["iced"], sizes: ["single"] },
      isSoldOut: false,
      isRecommended: true,
    },
  ];

  const orders = [];

  window.CafeData = Object.freeze({
    categories,
    menus,
    orders,
  });
})();
