(function () {
  const categories = [
    { id: "coffee", name: "Coffee", label: "커피", description: "에스프레소 기반의 기본 메뉴" },
    { id: "latte", name: "Latte", label: "라떼", description: "우유와 크림이 어우러진 부드러운 메뉴" },
    { id: "tea", name: "Tea", label: "티", description: "가볍게 즐기는 차와 허브 음료" },
    { id: "ade", name: "Ade", label: "에이드", description: "상큼한 레몬이 가득한 시그니처 음료" },
    { id: "dessert", name: "Dessert", label: "디저트", description: "상큼한 레몬 향 가득한 시그니처 디저트" },
  ];

  const menus = [
    {
      id: "americano",
      categoryId: "coffee",
      name: "아메리카노",
      englishName: "Americano",
      price: 4500,
      image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80",
      description: "깊고 깔끔한 산미가 살아 있는 기본 커피입니다.",
      tags: ["best", "hot", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "cafe-latte",
      categoryId: "latte",
      name: "카페라떼",
      englishName: "Cafe Latte",
      price: 5200,
      image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=900&q=80",
      description: "고소한 우유와 에스프레소가 균형 있게 어우러집니다.",
      tags: ["signature", "hot", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "vanilla-latte",
      categoryId: "latte",
      name: "바닐라 라떼",
      englishName: "Vanilla Latte",
      price: 5800,
      image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80",
      description: "은은한 바닐라 향을 더한 달콤한 라떼입니다.",
      tags: ["sweet", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "earl-grey",
      categoryId: "tea",
      name: "얼그레이 티",
      englishName: "Earl Grey Tea",
      price: 4800,
      image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=900&q=80",
      description: "베르가못 향이 산뜻하게 퍼지는 클래식 티입니다.",
      tags: ["hot", "light"],
      options: {
        temperature: ["hot"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "green-tea-latte",
      categoryId: "latte",
      name: "말차 라떼",
      englishName: "Green Tea Latte",
      price: 5900,
      image: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=900&q=80",
      description: "진한 말차와 우유의 부드러운 맛을 살렸습니다.",
      tags: ["signature", "sweet"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-ade",
      categoryId: "ade",
      name: "레몬에이드",
      englishName: "Lemon Ade",
      price: 5200,
      image: "/images/menu/lemon-ade.webp",
      description: "생레몬을 직접 짜서 만든 새콤달콤한 시그니처 에이드입니다.",
      tags: ["signature", "lemon", "iced"],
      options: {
        temperature: ["iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "honey-lemon-tea",
      categoryId: "ade",
      name: "허니레몬티",
      englishName: "Honey Lemon Tea",
      price: 5500,
      image: "/images/menu/honey-lemon-tea.jpg",
      description: "꿀과 레몬을 듬뿍 넣어 달콤하고 상큼하게 즐기는 티입니다.",
      tags: ["lemon", "sweet"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "lemon-mint-ade",
      categoryId: "ade",
      name: "레몬민트에이드",
      englishName: "Lemon Mint Ade",
      price: 5500,
      image: "/images/menu/lemon-mint-ade.jpg",
      description: "상큼한 레몬에 싱그러운 민트 향을 더해 청량감을 살렸습니다.",
      tags: ["lemon", "mint", "iced"],
      options: {
        temperature: ["iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-tart",
      categoryId: "dessert",
      name: "레몬 타르트",
      englishName: "Lemon Tart",
      price: 5800,
      image: "/images/menu/lemon-tart.jpg",
      description: "바삭한 타르트 시트 위에 상큼한 레몬 커드를 가득 채운 시그니처 디저트입니다.",
      tags: ["signature", "sour", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "lemon-pound-cake",
      categoryId: "dessert",
      name: "레몬 파운드케이크",
      englishName: "Lemon Pound Cake",
      price: 5200,
      image: "/images/menu/lemon-pound-cake.jpg",
      description: "촉촉한 버터 케이크에 레몬 글레이즈를 입혀 산뜻하게 마무리했습니다.",
      tags: ["sweet", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-cheesecake",
      categoryId: "dessert",
      name: "레몬 치즈케이크",
      englishName: "Lemon Cheesecake",
      price: 6500,
      image: "/images/menu/lemon-cheesecake.jpg",
      description: "진한 크림치즈에 레몬의 산미를 더해 느끼하지 않고 깔끔합니다.",
      tags: ["signature", "sour", "lemon"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
  ];

  const orders = [];

  window.CafeData = Object.freeze({
    categories,
    menus,
    orders,
  });
})();
